try {
    1 + 2;
} catch (error) {
    console.log("yaa");
} finally {
    console.log("ok");
}
